osixia/docker-openldap

- image/Dockerfile
- image/env.yml
- image/service/install.sh
- image/service/slapd/daemon.sh
Currently, the slapd log level is hardcoded to -1 (= all) in daemon.sh. While this is useful for debugging, it should be possible to trim down the amount of logging for production use.
This change allows the log level to be set via the environment LDAP_LOG_LEVEL.
(See table 5.1 in http://www.openldap.org/doc/admin24/slapdconf2.html for the available log levels.)
> Make log level configurable via environment variable

- image/service/slapd/container-start.sh
- image/service/slapd/daemon.sh
See https://github.com/docker/docker/issues/8231.
> Limit max open file descriptors to fix slapd memory usage

- image/service/slapd/startup.sh
This is a minor change but it helps a lot when the image is used for ldap integration testing and users are created using ldifs.
> Substitutes Base DN in custom ldif files

- image/service/slapd/assets/config/bootstrap/ldif/02-security.ldif
- image/service/slapd/assets/config/bootstrap/ldif/03-memberOf.ldif
- image/service/slapd/assets/config/bootstrap/ldif/04-refint.ldif
- image/service/slapd/assets/config/bootstrap/ldif/05-index.ldif
- image/service/slapd/assets/config/bootstrap/ldif/readonly-user/readonly-user-acl.ldif
- image/service/slapd/assets/config/replication/replication-disable.ldif
- image/service/slapd/assets/config/replication/replication-enable.ldif
- image/service/slapd/startup.sh
«The mdb backend to slapd(8) is the recommended primary backend for a
normal slapd database. It uses OpenLDAP's own Lightning Memory-Mapped
Database (LMDB) library to store data and is intended to replace the
Berkeley DB backends.
It supports indexing like the BDB backends, but it uses no caching and
requires no tuning to deliver maximum search performance. Like hdb, it
is also fully hierarchical and supports subtree renames in constant
time.»
http://www.openldap.org/doc/admin24/backends.html
> Use mdb over hdb

- image/service/slapd/startup.sh
The startup script incorrectly assumes bootstrap has been done already when it encounters any file in the data or config volumes. This obviously breaks when mounting in real volumes but might break in other cases as well.
> Ignore lost+found directories

- .gitignore
- README.md
- image/Dockerfile
I came to a situation, where i wanted to use this docker image as a base image for a project specific one with prepared test data in one case, and with a persistent data storage using volumes in another. Alas, since the LDAP storage directories are declared as volumes in the Dockerfile, it is not easily possible to deliver an image with volatile test data.
Since it is not possible to remove the volume command from a base image, I had to create a private branch of your repository, and apply my change. I think it would be beneficial for all users to drop the Volume command from the Dockerfile, as it does not forbid using volumes, but it forbids not using volumes.
See [https://github.com/docker/docker/pull/8177] for a discussion of removing volumes from base images.
> Remove Volume command from Dockerfile

- image/service/slapd/startup.sh
LDAP_BACKEND was not replaced for the readonly-user ldifs
> fixed LDAP_BACKEND for readonly user

- README.md
According to new stable man:
http://www.openldap.org/software/man.cgi?query=ldapsearch&apropos=0&sektion=0&manpath=OpenLDAP+2.4-Release&format=html
>        -H ldapuri
>               Specify URI(s) referring to the ldap server(s); a list  of  URI,
>               separated   by  whitespace  or  commas  is  expected;  only  the
>               protocol/host/port fields are allowed.  As an exception,  if  no
>               host/port  is  specified, but a DN is, the DN is used to look up
>               the corresponding host(s) using the DNS SRV  records,  according
>               to  RFC 2782.  The DN must be a non-empty sequence of AVAs whose
>               attribute type is "dc" (domain component), and must  be  escaped
>               according to RFC 2396.
> 
>        -h ldaphost
> …
> README.md - change deprecated '-h' to now favoured '-H ldap://'

- image/service/slapd/test.sh
- test/test.bats
- test/test_helper.bash
Fixes issue #90 
Test data in test/{ssl,config,database} were previously affected by running tests, especially by in-container scripts changing permissions/owner. This could lead to problems in a CI environment, such as files changing ownership and being unable to be automatically removed. 
ssl certificates are now copied by --copy-service and refered to via /container/run,
and database/config are mapped to /container/test instead which can be copied to the right place by calling test.sh script bundled in image (via --cmd runtime option)
Note that this does not affect actual resulting container image save for the addition of test.sh which is unused unless explicitly called via --cmd
> Make BATS testing not affect base test data, allowing easier CI integration

- image/Dockerfile
Hi,
In order to enable SASL mechanism, the following packages must be installed. Would you like to embed them in the container image ?
Regards,
Étienne
> Install libsasl2 modules

- README.md
Removed and added a whitespace after `####` so that **Use your own certificate** is marked as a heading and is linkable.
> Fixed readme heading

- README.md
- image/Dockerfile
I am using the image in a setup where we are required to use specific uid and gid for the ldap database. This pull request adds the capability to do so.
Build parameters LDAP_OPENLDAP_UID and LDAP_OPENLDAP_GID can be used
to set the uid and gid of the openldap user explicitly.
> Enable matching uid's and gid's in the host and container.

- README.md
- image/service/slapd/assets/config/bootstrap/ldif/custom/README.md
- image/service/slapd/startup.sh
This PR adds support of readonly users attributes LDAP_READONLY_USER_USERNAME and LDAP_READONLY_USER_PASSWORD_ENCRYPTED to custom ldif scripts.
> Add support of readonly user in custom bootstrap ldif

- image/service/slapd/startup.sh
@BertrandGouny that should do it, would be great if someone could double check it (init a new server and check that the schema is generated in alphabetical order).
Btw would you accept and env var to disable the default mmc schemas?
> Create schemas in a consistent order.

- image/service/slapd/startup.sh
`find` doesn't sort the output, but if you don't sort it and two schema files are dependent on each other (schema 2 uses an attribute defined in schema 1) the startup of the container will fail if `find` doesn't happen to return in the order needed. By sorting it you can know/rely on asciibetical sorting to ensure the schema files get included in the right order.
Also, this isn't needed if instead of `find` you use `for f in /path/to/*.schema` as the glob already returns in asciibetical order. Makes for one less call to a binary too.
> startup.sh: Ensure SCHEMAS is sorted

- image/service/slapd/startup.sh
The former check is ambigious with similiar schema names.
Example:
Installed schema: `core-fd-conf`
New schema: `core-fd`
Previously the schema `core-fd` could not be installed because the schema check was ambigious with `core-fd-conf`.
This problem came up when installing schemas for fusiondirectory.
> Remove schema ambiguity

- image/service/slapd/startup.sh
This MR provides more generic fix for the issue #168 
Volumes mounted by different provider usually contain temporary or trash folders which names starting with `.` So ignoring such folders make startup less error-prone.
> ignore all the folders started with . 

- image/service/slapd/assets/config/bootstrap/ldif/readonly-user/readonly-user-acl.ldif
The security issue fixed in version 1.2.1 is still there when a read-only user is created.
> Fix self-edit security issue

- README.md
As requested in issue #159 there is no information about how to access the ldap server from outside the container. Added a small hint in the quickstart about the port mapping.
> Added information about port mapping

- README.md
- image/service/slapd/startup.sh
This pull request:
* Updates the reference to the official site of bats
* Fixes a small mistake in the implementation of DISABLE_CHOWN. The current implementation makes some of the UT to fail. I am guessing that we should have compared the variable to false, instead of true. 
I hope it is useful.
If something is not clear (or wrong), please let me know and I will try to explain it (fix it) :)
> Updating the reference to bats and fixing the UT

- README.md
- image/service/slapd/startup.sh
- test/test.bats
The merge request implements support for docker secrets. 
More or less it allows you to do:
```
version: '3.3'
services:
openldap:
image: anagno/openldap:latest
environment:
LDAP_DOMAIN: "anagno.me"
LDAP_ORGANISATION: "anagno"
LDAP_ADMIN_PASSWORD_FILE: /run/secrets/authentication_admin_pw
LDAP_CONFIG_PASSWORD_FILE: /run/secrets/authentication_config_pw
LDAP_READONLY_USER: "true"
LDAP_READONLY_USER_USERNAME: "readonly"
LDAP_READONLY_USER_PASSWORD_FILE: /run/secrets/authentication_readonly_pw
secrets:
- authentication_admin_pw
- authentication_config_pw
- authentication_readonly_pw
secrets:
authentication_admin_pw:
external: true
authentication_config_pw:
external: true
authentication_readonly_pw:
external: true
```
It follows the same pattern that the postgesql …
> Support for docker secrets

- image/service/slapd/startup.sh
exit codes of ldapmodify and ldapadd commands were invalidated by " | log-helper debug" and therefore OR operator || was not working as intended
> fix of incorrectly positioned 'log-helper debug' command

- image/service/slapd/startup.sh
- test/test.bats
- test/test_helper.bash
Plus some minor additions/fixes
> Fix domain dn

- image/environment/default.yaml
- image/service/slapd/process.sh
This PR adds the ability to specify the ports where OpenLDAP will listen for LDAP and LDAPS protocols. By default they are set to the standard 389 and 636 respectively and they can be overriden by setting the `LDAP_PORT` and/or `LDAPS_PORT` at runtime.
I think this fixes https://github.com/osixia/docker-openldap/issues/165
> Allow setting ports on ldap and ldaps

- image/service/slapd/assets/config/bootstrap/ldif/02-security.ldif
- image/service/slapd/assets/config/bootstrap/ldif/readonly-user/readonly-user-acl.ldif
Fixes the Issues:
- #402 
- #413 
Adds an acl to explicitly grant 'root' rights to modify the ldap database, otherwise 
```
ldapmodify -Y EXTERNAL -H ldapi:/// -f <FILE>
```
fails.
I've built and uploaded the image to dockerhub: [oliadev/openldap:1.3.0](https://hub.docker.com/r/oliadev/openldap)
> [FIX] #402: grant root manage access to database

- README.md
Docker Engine doesn't work well with firewall-cmd and can cause issues if you're connecting to the LDAP server from another container on the same machine. 
https://github.com/moby/moby/issues/32138
> Address firewall issues on RHEL in README

- image/service/slapd/startup.sh
- test/test.bats
> Better handling of environment variables checks

- image/Dockerfile
Otherwise Letsencrypt (and other new CAs) certs do not validate.
> Ensure ca certs are up to date

- image/Dockerfile
#235 discusses inclusion of the pbkdf2 password hash support for openldap. The solution is quite easy - simply add the slapd-contrib module, leading to the following new files
```
root@ae97956e7665:/etc# dpkg -L slapd-contrib
/.
/usr
/usr/lib
/usr/lib/ldap
/usr/lib/ldap/pw-apr1.la
/usr/lib/ldap/pw-apr1.so.0.0.0
/usr/lib/ldap/pw-netscape.la
/usr/lib/ldap/pw-netscape.so.0.0.0
/usr/lib/ldap/pw-pbkdf2.la
/usr/lib/ldap/pw-pbkdf2.so.0.0.0
/usr/lib/ldap/smbk5pwd.la
/usr/lib/ldap/smbk5pwd.so.0.0.0
/usr/share
/usr/share/doc
/usr/share/doc/slapd-contrib
/usr/share/doc/slapd-contrib/changelog.Debian.gz
/usr/share/doc/slapd-contrib/changelog.gz
/usr/share/doc/slapd-contrib/copyright
/usr/share/doc/slapd-contrib/examples
/usr/share/doc/slapd-contrib/examples/apr1-atol.pl …
```
> Install slapd-contrib to include pbkdf2 pw support

- README.md
Hi :fr: 
I did some improvements and fixed on typo (line 222)
> Improved the README.md

- README.md
Add note indicating that the read-only user account can write its own password.
This was a little confusing to me, but I guess it makes sense. I think a note would still help, though.
> Add Note About Read-only User Password

- example/docker-compose.yml
If `LDAP_REPLICATION_CONFIG_SYNCPROV` and `LDAP_REPLICATION_DB_SYNCPROV` are enabled, it will cause an error.
```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
ERROR: yaml.parser.ParserError: while parsing a block mapping
in "./docker-compose.yml", line 7, column 7
expected <block end>, but found '<scalar>'
in "./docker-compose.yml", line 27, column 50
```
> fix invalid format in docker-compose.yml

- image/service/slapd/assets/config/bootstrap/ldif/custom/README.md
This is already documented in the main README file but is missing from this one.
> Add missing LDAP_DOMAIN substitution to custom LDIF README

- image/Dockerfile
This PR solves the issue:  https://github.com/osixia/docker-openldap/issues/461
In my opinion using e.g. 2.4.57\* is clear/accurate enough to specific the version.
> Use specific version for ldap-utils and slapd-contrib

- image/service/slapd/startup.sh
Hi I'm using this image and trying to use customize ldfi file when initial, but this feature seem doesn't work
After I check startup.sh I find this issue
in line 44 should use ${CONTAINER_SERVICE_DIR}, 
because when using `--copy-service` the ${CONTAINER_SERVICE_DIR} will be /container/run/service
and the custom boostrap ldif execution in line 366 is using `${CONTAINER_SERVICE_DIR}/slapd/assets/config/bootstrap/ldif/custom`
> fix custom ldap file and schema

- image/Dockerfile
Fixes https://github.com/osixia/docker-openldap/issues/506
Fixes #504 (together with other PR #525)
Follup-up from https://github.com/osixia/docker-light-baseimage/pull/30
> Update to baseimage v1.3.1 to fix expired default-ca

- image/service/slapd/startup.sh
fixes #532 by allowing to set LDAP_REPLICATION="own" to provide own replication settings via custom bootstrap ldifs.
Whether this should set WAS_STARTED_WITH_REPLICATION, or not, can be debated.
> Allowing own replication via LDAP_REPLICATION=own
